version: "3.8"

services:
  fastify-app:
    build: .
    container_name: fastify_app
    ports:
      - "3002:3002"  # Updated port
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    container_name: sqlite_db
    volumes:
      - ./src/app.db:/app/app.db
